=== j2me-preservation/midpath/resources-embedded/com/sun/midp/configuration/configuration.dtd
<!--

        Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
-->
<!ELEMENT configuration (properties | constants | localized_strings | skin | rawimage)*>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>

<!ELEMENT localized_strings (localized_string)*>
    
<!-- 
    KeysClass: name of constants class that provides keys values.   
 -->
<!ATTLIST localized_strings
    Package     CDATA                           #REQUIRED
    Name        CDATA                           #REQUIRED
    KeysClass   CDATA                           #REQUIRED 
    Scope       (protected | public)            "public"
    Comment     CDATA                           #IMPLIED
>
<!ELEMENT localized_string EMPTY>
<!ATTLIST localized_string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!ELEMENT constants (constant_class)*>
<!ELEMENT constant_class (constant)*>

<!--
    KeysValuesProvider: does this class provide keys values.
    
    AutoValue: automatically generate integer values for constants
    (starting from zero and going up).

    JavaOnly: generate only .java file for constants.
-->
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
    KeysValuesProvider (true | false)        "false"
    AutoValue (true | false)                "false"
    JavaOnly  (true | false)                "false"
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type      (int | String | boolean)       #IMPLIED
    Name      CDATA                          #REQUIRED
    Value     CDATA                          #IMPLIED
    VScope    (protected | public | private) "public"
    Comment   CDATA                          #IMPLIED
>

<!--
    Top level node for skin description
-->
<!ELEMENT skin (skin_properties)>


<!--
    Skin properties description
-->
<!ELEMENT skin_properties (integer | integer_seq | string | font | 
        image | composite_image)+>
<!ATTLIST skin_properties
    KeysClass   CDATA                           #REQUIRED 
>

<!--
    Integer valued skin property
-->
<!ELEMENT integer EMPTY>
<!ATTLIST integer
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Integers sequence valued skin property
-->
<!ELEMENT integer_seq EMPTY>
<!ATTLIST integer_seq
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    String valued skin property
-->
<!ELEMENT string EMPTY>
<!ATTLIST string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Font valued skin property
-->
<!ELEMENT font EMPTY>
<!ATTLIST font
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Image valued skin property
-->
<!ELEMENT image EMPTY>
<!ATTLIST image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Composite image valued skin property
-->
<!ELEMENT composite_image EMPTY>
<!ATTLIST composite_image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Pieces      CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Raw image format description
-->
<!ELEMENT rawimage EMPTY>
<!ATTLIST rawimage
        Format    (Putpixel | ARGB)         #REQUIRED
        Colors    (565 | 888)               #REQUIRED
        Endian    (Little | Big)            #REQUIRED
>

=== j2me-preservation/midpath/resources-embedded/com/sun/midp/configuration/constants_open.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--

        Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER

-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
  <constant Type="int"
            Name="MAX_ISOLATES"
            Value="8"
            Comment="MAX_ISOLATES"/>

  <constant Type="int"
            Name="SUITE_MEMORY_RESERVED"
            Value="100"
            Comment="Default MIDletSuite memory reserved."/>
  <constant Type="int"
            Name="SUITE_MEMORY_LIMIT"
            Value="-1"
            Comment="Default MIDletSuite Memory Limit."/>

  <constant Type="int"
            Name="TCP_CLI_GLOBAL_LIMIT"
            Value="16"
            Comment="Global resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_AMS_RESERVED"
            Value="2"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_AMS_LIMIT"
            Value="(TCP_CLI_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_SUITE_LIMIT"
            Value="(TCP_CLI_GLOBAL_LIMIT - TCP_CLI_AMS_RESERVED)"
            Comment="Per suite resource limit for TCP client sockets"/>

  <constant Type="int"
            Name="TCP_SER_GLOBAL_LIMIT"
            Value="12"
            Comment="Global resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_AMS_LIMIT"
            Value="(TCP_SER_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_SUITE_LIMIT"
            Value="(TCP_SER_GLOBAL_LIMIT - TCP_SER_AMS_RESERVED)"
            Comment="Per suite resource limit for TCP server sockets"/>

  <constant Type="int"
            Name="UDP_GLOBAL_LIMIT"
            Value="12"
            Comment="Global resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_AMS_LIMIT"
            Value="(UDP_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_SUITE_LIMIT"
            Value="(UDP_GLOBAL_LIMIT - UDP_AMS_RESERVED)"
            Comment="Per suite resource limit for UDP sockets"/>

  <constant Type="int"
            Name="FILE_GLOBAL_LIMIT"
            Value="30"
            Comment="Global resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_AMS_RESERVED"
            Value="6"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_AMS_LIMIT"
            Value="(FILE_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_SUITE_RESERVED"
            Value="4"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_SUITE_LIMIT"
            Value="(FILE_GLOBAL_LIMIT - FILE_AMS_RESERVED)"
            Comment="Per suite resource limit for File handlers"/>

  <constant Type="int"
            Name="AUDIO_CHA_GLOBAL_LIMIT"
            Value="5"
            Comment="Global resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_AMS_LIMIT"
            Value="(AUDIO_CHA_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_SUITE_LIMIT"
            Value="(AUDIO_CHA_GLOBAL_LIMIT - AUDIO_CHA_AMS_RESERVED)"
            Comment="Per suite resource limit for Audio channels"/>

  <constant Type="int"
            Name="IMAGE_MUT_GLOBAL_LIMIT"
            Value="1000000"
            Comment="Global resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_AMS_LIMIT"
            Value="(IMAGE_MUT_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_SUITE_LIMIT"
            Value="(IMAGE_MUT_GLOBAL_LIMIT - IMAGE_MUT_AMS_RESERVED)"
            Comment="Per suite resource limit for mutable images"/>

  <constant Type="int"
            Name="IMAGE_IMMUT_GLOBAL_LIMIT"
            Value="1300000"
            Comment="Global resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_AMS_LIMIT"
            Value="(IMAGE_IMMUT_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_SUITE_LIMIT"
            Value="(IMAGE_IMMUT_GLOBAL_LIMIT - IMAGE_IMMUT_AMS_RESERVED)"
            Comment="Per suite resource limit for immutable images"/>
 </constant_class>
</constants>
</configuration>

=== j2me-preservation/midpath/resources-embedded/com/sun/midp/configuration/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "./configuration.dtd">
<!--

		Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
		DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
-->
<!-- Properties file common for all platforms -->
<configuration>
<properties>
<!-- INTERNAL PROPERTIES -->
<!-- Visible from Configuration.getProperty() -->
  <!-- System tunable parameters -->

  <property Key="destroyMIDletTimeout"
	  Value="5"
	  Scope="internal"
	  Comment="Destroy MIDlet timeout"/>

  <property Key="system.jam_space"
	  Value="1000000"
	  Scope="internal"
	  Comment="Amount of space to reserve for JAM storage."/>

  <property Key="system.i18n.lang"
	  Value="en"
	  Scope="internal"
	  Comment="Default language for I18N processing."/>      
  <property Key="system.i18n.encoding"
	  Value="ISO8859_1"
	  Scope="internal"
	  Comment="Default encoding for I18N processing."/>
      
  <!-- serial port buffering is on by default to support available() -->
  <!-- property Key="com.sun.midp.io.j2me.comm.buffersize"
				Value="256"
				Scope="internal"/> -->

  <!-- TCP buffering is off by default -->
  <!-- property Key="com.sun.midp.io.j2me.socket.buffersize"
				Value="0"
				Scope="internal"/> -->

  <property Key="com.sun.midp.lcdui.eventHandler"
	  Value="com.sun.midp.lcdui.DefaultEventHandler"
	  Scope="internal"
	  Comment="Default event handler class."/>
  <property Key="com.sun.midp.lcdui.inputHandler"
	  Value="com.sun.midp.lcdui.DefaultInputMethodHandler"
	  Scope="internal"
	  Comment="Default input handler class."/>

  <!-- property Key="com.sun.midp.io.http.proxy" 
				Value="webcache:8080" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.force_non_persistent" 
				Value="false" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.persistent_connection_linger_time" 
				Value="60000" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.input_buffer_size" 
				Value="256" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.output_buffer_size" 
				Value="2048" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.max_persistent_connections" 
				Value="4" 
				Scope="internal"/ -->

  <!-- Event queue dispatch table tuning -->
  <!-- property Key="com.sun.midp.events.dispatchTableInitSize" 
				Value="16" 
				Scope="internal"/ -->
      
  <property Key="VmDebuggerPort"
	  Value="2808"
	  Scope="internal"
	  Comment="VM debugger port number."/>
      
      
  <property Key="DisableStartupErrorAlert"
	  Value="0"
	  Scope="internal"
	  Comment="If not 0, don't display start up errors in a
                  Java Alert."/>
      
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->

  <property Key="microedition.hostname" 
		Value="" 
		Scope="system"
		Callout="getLocalHostName"
		Comment="The local hostname."/>
  <property Key="microedition.configuration" 
		Value="CLDC-1.1" 
		Scope="system"
		Comment="Configuration information."/>
  <property Key="microedition.profiles" 
		Value="MIDP-2.0" 
		Scope="system"
		Comment="Profile information."/>
  <property Key="microedition.locale" 
		Value="en-US"
		Scope="system"
		Comment="System locale."/>
  <property Key="microedition.platform" 
		Value="j2me" 
		Scope="system"
		Comment="Platform name."/>
  <!-- property Key="microedition.encoding" 
		Value="ISO8859_1" 
		Scope="system"/ -->
  <property Key="microedition.commports" 
		Value="&quot;&quot;" 
		Scope="system"/>
  <property Key="microedition.jtwi.version" 
		Value="1.0" 
		Scope="system"
		Comment="JWTI version number."/>

  <!-- CLDC implementation parameters -->
  <!-- use MIDP protocol implementations -->
  <property Key="javax.microedition.io.Connector.protocolpath" 
		Value="com.sun.midp.io"
		Scope="system"
		Comment=""/>
  <!-- property Key="java.lang.Character.caseConverter" 
		Value="com.sun.cldc.i18n.uclc.DefaultCaseConverter" 
		Scope="system"/ -->
  <!-- property Key="com.sun.cldc.i18n.Helper.i18npath" 
		Value="com.sun.cldc.i18n.j2me" 
		Scope="system"/ -->
  <!-- property Key="microedition.implpath"
		Value="com.sun.cldc" 
		Scope="system"/ -->
  <property Key="com.sun.cldc.util.j2me.TimeZoneImpl.timezone" 
		Value="" 
		Scope="system"
		Callout="getLocalTimeZone"
		Comment="System function of getting local time zone."/>
</properties>
</configuration>

=== j2me-preservation/midpath/src/com/sun/midp/configuration/constants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "./configuration.dtd">
<!--

        Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
-->
<configuration>
<constants>
<!-- Package com.sun.midp.log -->
<constant_class Package="com.sun.midp.log" Name="LogChannels" Scope="public"
    Comment="/** Channel definitions generated by the configurator utility */">
  <constant Type="int"
            Name="LC_NONE"
            Value="0"
            Comment="No channel specified"/>
  <constant Type="int"
            Name="LC_AMS"
            Value="500"
            Comment="AMS module channel"/>
  <constant Type="int"
            Name="LC_CORE"
            Value="1000"
            Comment="Core module channel"/>
  <constant Type="int"
            Name="LC_MIDPSTRING"
            Value="1100"
            Comment="Core midpString channel"/>
  <constant Type="int"
            Name="LC_MALLOC"
            Value="1200"
            Comment="Core malloc channel"/>
  <constant Type="int"
            Name="LC_CORE_STACK"
            Value="1300"
            Comment="Core stack usage tracing channel"/>
  <constant Type="int"
            Name="LC_LOWUI"
            Value="2000"
            Comment="Low level UI module channel"/>
  <constant Type="int"
            Name="LC_I18N"
            Value="3000"
            Comment="I18N module channel"/>
  <constant Type="int"
            Name="LC_HIGHUI"
            Value="4000"
            Comment="High level UI module channel"/>
  <constant Type="int"
            Name="LC_HIGHUI_ITEM_LAYOUT"
            Value="4100"
            Comment="High level UI item layout channel"/>
  <constant Type="int"
            Name="LC_HIGHUI_ITEM_REPAINT"
            Value="4200"
            Comment="High level UI item repaint channel"/>
  <constant Type="int"
            Name="LC_HIGHUI_FORM_LAYOUT"
            Value="4300"
            Comment="High level UI form layout channel"/>
  <constant Type="int"
            Name="LC_HIGHUI_ITEM_PAINT"
            Value="4400"
            Comment="High level UI form paint channel"/>
  <constant Type="int"
            Name="LC_PROTOCOL"
            Value="5000"
            Comment="Protocol module channel"/>
  <constant Type="int"
            Name="LC_RMS"
            Value="6000"
            Comment="RMS module channel"/>
  <constant Type="int"
            Name="LC_SECURITY"
            Value="7000"
            Comment="Security module channel"/>
  <constant Type="int"
            Name="LC_SERVICES"
            Value="8000"
            Comment="Services module channel"/>
  <constant Type="int"
            Name="LC_TOOL"
            Value="9000"
            Comment="Tools module channel"/>
  <constant Type="int"
            Name="LC_JSR180"
            Value="10000"
            Comment="JSR180 module channel"/>
  <constant Type="int"
            Name="LC_EVENTS"
            Value="9500"
            Comment="Event queue module channel"/>
  <constant Type="int"
            Name="LC_STORAGE"
            Value="10000"
            Comment="File Storage module channel"/>
  <constant Type="int"
            Name="LC_PUSH"
            Value="10500"
            Comment="Push registry module channel"/>
</constant_class>
<!-- Memory limits -->
<constant_class Package="com.sun.midp.configurator" Name="Constants"
                Scope="public">
  <constant Type="int"
            Name="LOG_INFORMATION"
            Value="0"
            Comment="Logging level used to report information that is not
                    associated with any significant condition."/>
  <constant Type="int"
            Name="LOG_WARNING"
            Value="1"
            Comment="Logging level used to report unexpected conditions that are
                    typically fully recoverable."/>
  <constant Type="int"
            Name="LOG_ERROR"
            Value="2"
            Comment="Logging level used to report unexpected conditions that are
                    typically at least partially recoverable."/>
  <constant Type="int"
            Name="LOG_CRITICAL"
            Value="3"
            Comment="Logging level used to report unexpected conditions that are
                typically not recoverable, or are catastrophic to the system."/>
  <constant Type="int"
            Name="LOG_DISABLED"
            Value="4"
            Comment="Logging level used to disable all output and all logging
                    calls will be compiled out of the build."/>
  <constant Type="int"
            Name="REPORT_LEVEL"
            Value="LOG_ERROR"
            Comment="Threshhold for the severity level below which
                    log messages will not be recorded. Severity levels less
                    than this value can be compiled out of the build."/>
  <constant Type="int"
            Name="AMS_MEMORY_RESERVED_MVM"
            Value="1024"
            Comment="Default AMS memory reserved in MVM mode"/>
  <constant Type="int"
            Name="AMS_MEMORY_LIMIT_MVM"
            Value="-1"
            Comment="Default AMS memory limit in MVM mode"/>
  <constant Type="int"
            Name="MIDLET_CONSTRUCTOR_FAILED"
            Value="-1"
            Comment="MIDlet start error status, when a MIDlet's constructor
                    fails to catch a runtime exception"/>
  <constant Type="int"
            Name="MIDLET_SUITE_NOT_FOUND"
            Value="-2"
            Comment="MIDlet start error status,
                    when a MIDlet suite is not found"/>
  <constant Type="int"
            Name="MIDLET_CLASS_NOT_FOUND"
            Value="-3"
            Comment="MIDlet start error status, when a class needed to
                    create a MIDlet is not found."/>
  <constant Type="int"
            Name="MIDLET_INSTANTIATION_EXCEPTION"
            Value="-4"
            Comment="MIDlet start error status, when intantiation exception is
                    thrown during the intantiation of a MIDlet."/>
  <constant Type="int"
            Name="MIDLET_ILLEGAL_ACCESS_EXCEPTION"
            Value="-5"
            Comment="MIDlet start error status, when illegal access exception
                    is thrown during the intantiation of a MIDlet."/>
  <constant Type="int"
            Name="MIDLET_OUT_OF_MEM_ERROR"
            Value="-6"
            Comment="MIDlet start error status, when a MIDlet's constructor
                    runs out of memory."/>
  <constant Type="int"
            Name="MIDLET_RESOURCE_LIMIT"
            Value="-7"
            Comment="MIDlet start error status, when a the system cannot
                     reserve enough resource to start a MIDlet suite."/>
  <constant Type="int"
            Name="MIDLET_ISOLATE_CONSTRUCTOR_FAILED"
            Value="-9"
            Comment="MIDlet start error status, when a MIDlet's isolate
                     constructor throws to catch a runtime exception"/>
  <constant Type="int"
            Name="MIDLET_ID_NOT_GIVEN"
            Value="-10"
            Comment="MIDlet start error status, when a MIDlet's ID
                     is not given"/>
  <constant Type="int"
            Name="MIDLET_CLASS_NOT_GIVEN"
            Value="-11"
            Comment="MIDlet start error status, when a MIDlet's class
                     is not given"/>
  <constant Type="int"
            Name="MIDLET_SUITE_DISABLED"
            Value="-12"
            Comment="MIDlet start error status, when a MIDlet's suite
                     is disabled"/>
  <constant Type="int"
            Name="MIDLET_ISOLATE_RESOURCE_LIMIT"
            Value="-13"
            Comment="MIDlet start error status, when system has exceeded
                     the maximum Isolate count."/>
  <constant Type="int"
            Name="MIDLET_APPID_NO_FOREGROUND"
            Value="0"
            Comment="Reserved external application id for setting
                    no MIDlet in foreground"/>
  <constant Type="int"
            Name="MAX_INSTALL_DELETE_NOTIFICATION_RETRIES"
            Value="5"
            Comment="Number of times an install or delete notification
                    has to be retried by the notification manager"/>
</constant_class>
</constants>
</configuration>

=== j2me-preservation/midpath/src/com/sun/midp/configuration/mmapi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--

        Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
-->
<!-- THIS IS THE MMAPI PROPERTIES FILE FOR SHARP ZAURUS 5500D ONLY!
     YOU MAY NEED TO ADJUST THAT TO YOUR PLATFORM -->
<configuration>
<properties>
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->
<property Key="microedition.media.version" 
	  Value="1.1" 
	  Scope="system"/>
<property Key="supports.mixing" 
	  Value="true" 
	  Scope="system"/>
<property Key="supports.audio.capture" 
	  Value="true" 
	  Scope="system"/>
<property Key="supports.video.capture" 
	  Value="true"
	  Scope="system"/>
<property Key="supports.recording" 
	  Value="true" 
	  Scope="system"/>
<property Key="audio.encodings" 
	  Value="encoding=pcm" 
	  Scope="system"/>
<property Key="video.snapshot.encodings" 
	  Value="encoding=jpeg" 
	  Scope="system"/>
<property Key="streamable.contents" 
	  Value="audio/x-wav" 
	  Scope="system"/>
<property Key="video.encodings" 
	  Value="encoding=rgb565 encoding=rgb565&amp;width=160&amp;height=120 encoding=rgb565&amp;width=120&amp;height=160 encoding=rgb565&amp;width=240&amp;height=320 encoding=rgb565&amp;width=480&amp;height=640 encoding=rgb565&amp;width=320&amp;height=240 encoding=rgb565&amp;width=480&amp;height=320"
	  Scope="system"/>
</properties>
</configuration>
